import {useEffect,useRef,useState} from 'react';
import {Alert,Input,Modal,Space,Table,TreeSelect} from 'antd';
import {ConfiguredButton as Button} from '../../components/ConfiguredButton';
import {usersApi,type UserDirectoryPage} from '../../api/users';
import {organizationApi,type OrganizationNode} from '../../api/organization';
import {organizationChoices} from './CreateUserDrawer';
interface Props{open:boolean;title:string;actionPrefix:string;existingUserIds?:string[];existingRelations?:{userId:string;organizationId:string|null}[];requireOrganization?:boolean;targetOrganizationId?:string;administratorMode?:boolean;onClose:()=>void;onSubmit:(ids:string[],organizationId:string|null)=>Promise<void>;}
export function UserPickerModal({open,title,actionPrefix,existingUserIds=[],existingRelations=[],requireOrganization=false,targetOrganizationId,administratorMode=false,onClose,onSubmit}:Props){
 const [directory,setDirectory]=useState<UserDirectoryPage>({items:[],page:1,pageSize:20,total:0});const [organizations,setOrganizations]=useState<OrganizationNode[]>([]);const [scope,setScope]=useState<string>();const [keyword,setKeyword]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState<string[]>([]);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string>();const request=useRef(0);const saving=useRef(false);
 const [ready,setReady]=useState(false);const [knownMembers,setKnownMembers]=useState<string[]>([]);
 const disabled=new Set([...knownMembers,...existingUserIds,...existingRelations.filter(r=>r.organizationId===(scope??null)).map(r=>r.userId)]);
 async function load(page=1,search=query,organization=scope){if(requireOrganization&&!organization)return;const serial=++request.current;setLoading(true);setReady(false);setDirectory({items:[],page,pageSize:20,total:0});setError(undefined);try{const data=await(requireOrganization?organizationApi.members(organization!,{page,pageSize:20,keyword:search}):usersApi.list({page,pageSize:20,keyword:search,status:'ENABLED'}));const relations=targetOrganizationId&&data.items.length?await organizationApi.memberRelations(targetOrganizationId,data.items.map(u=>u.id)):[];if(serial===request.current){setDirectory(data);setReady(true);const locked=relations.filter(r=>!administratorMode||r.administrator).map(r=>r.userId);setKnownMembers(previous=>[...new Set([...previous,...locked])]);setSelected(previous=>previous.filter(id=>!locked.includes(id)));}}catch(e){if(serial===request.current)setError(e instanceof Error?e.message:'用户加载失败');}finally{if(serial===request.current)setLoading(false);}}
 useEffect(()=>{if(open){setScope(undefined);setSelected([]);setKnownMembers([]);setReady(false);setKeyword('');setQuery('');setError(undefined);if(requireOrganization){setDirectory({items:[],page:1,pageSize:20,total:0});const serial=++request.current;setLoading(true);void organizationApi.listTree().then(data=>{if(serial===request.current)setOrganizations(data);}).catch(e=>{if(serial===request.current)setError(e instanceof Error?e.message:'组织加载失败');}).finally(()=>{if(serial===request.current)setLoading(false);});}else void load(1,'');}return()=>{request.current++;};},[open,requireOrganization]);
 async function save(){if(saving.current||!selected.length||loading||!ready||(requireOrganization&&!scope))return;saving.current=true;setBusy(true);setError(undefined);try{await onSubmit(selected,scope??null);onClose();}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{saving.current=false;setBusy(false);}}
 return <Modal title={title} centered open={open} width="min(800px,92vw)" onCancel={busy?undefined:onClose} closable={!busy} maskClosable={!busy} keyboard={!busy} footer={[<Button actionKey={`${actionPrefix}.cancel`} key="cancel" disabled={busy} onClick={onClose}>取消</Button>,<Button actionKey={`${actionPrefix}.save`} key="save" type="primary" loading={busy} disabled={!selected.length||loading||!ready||(requireOrganization&&!scope)} onClick={()=>void save()}>保存关联</Button>]}>
 {error&&<Alert type="error" message={error}/>}
 <Space wrap style={{marginBottom:16}}>{requireOrganization&&<TreeSelect aria-label="关联组织" placeholder="选择组织" style={{width:240}} showSearch treeNodeFilterProp="title" treeData={organizationChoices(organizations)} disabled={busy} value={scope} onChange={id=>{setScope(id);setSelected([]);setKnownMembers([]);setReady(false);setQuery('');setKeyword('');void load(1,'',id);}}/>}<Input aria-label="关联用户查询" placeholder="账号或名称" style={{width:240}} value={keyword} disabled={busy} onChange={e=>setKeyword(e.target.value)} onPressEnter={()=>{setQuery(keyword);void load(1,keyword);}}/><Button actionKey={`${actionPrefix}.query`} disabled={busy||(requireOrganization&&!scope)} onClick={()=>{setQuery(keyword);void load(1,keyword);}}>查询</Button><span>已选 {selected.length} 人</span></Space>
 <Table rowKey="id" size="small" loading={loading} dataSource={directory.items} scroll={{y:Math.max(180,window.innerHeight-390)}} columns={[{title:'账号',dataIndex:'username'},{title:'名称',dataIndex:'displayName'},{title:'状态',dataIndex:'status',render:status=>status==='ENABLED'?'启用':status==='DISABLED'?'停用':status==='LOCKED'?'锁定':'已注销'}]} rowSelection={{selectedRowKeys:[...new Set([...selected,...disabled])],preserveSelectedRowKeys:true,onChange:keys=>setSelected(keys.map(String).filter(id=>!disabled.has(id))),getCheckboxProps:u=>({disabled:busy||loading||!ready||disabled.has(u.id)||u.status!=='ENABLED'})}} pagination={{current:directory.page,pageSize:20,total:directory.total,showSizeChanger:false,onChange:page=>void load(page)}}/>
 </Modal>;
}
