import {render,screen,fireEvent,waitFor} from '@testing-library/react';import {it,expect,vi} from 'vitest';import {UserPickerModal} from './UserPickerModal';import {usersApi} from '../../api/users';import {organizationApi} from '../../api/organization';
vi.mock('../../api/users',()=>({usersApi:{list:vi.fn()}}));
vi.mock('../../api/organization',()=>({organizationApi:{listTree:vi.fn(),members:vi.fn(),memberRelations:vi.fn()}}));
it('已有用户只读，勾选新用户一次提交，失败保留选择',async()=>{vi.mocked(usersApi.list).mockResolvedValue({items:[{id:'old',displayName:'已有用户',username:'old',status:'ENABLED'},{id:'new',displayName:'新增用户',username:'new',status:'ENABLED'}],page:1,pageSize:20,total:2} as any);const submit=vi.fn().mockRejectedValue(new Error('整批失败'));render(<UserPickerModal open title="关联用户" onClose={()=>{}} onSubmit={submit} existingUserIds={['old']} actionPrefix="iam.role-users"/>);await screen.findByText('新增用户');const checkboxes=screen.getAllByRole('checkbox');expect(checkboxes[1]).toBeDisabled();fireEvent.click(checkboxes[2]);fireEvent.click(screen.getByRole('button',{name:'保存关联'}));await waitFor(()=>expect(submit).toHaveBeenCalledWith(['new'],null));await screen.findByText('整批失败');expect(checkboxes[2]).toBeChecked();});

it('候选用户逐页读取目标组织关系，已有成员只读且已勾选',async()=>{vi.mocked(usersApi.list).mockResolvedValue({items:[{id:'existing',displayName:'其他页已有成员',username:'exists',status:'ENABLED'}],page:1,pageSize:20,total:1} as any);vi.mocked(organizationApi.memberRelations).mockResolvedValue([{userId:'existing',administrator:false}]);render(<UserPickerModal open title="关联用户" onClose={()=>{}} onSubmit={async()=>{}} actionPrefix="organizations.member-picker" targetOrganizationId="org"/>);await screen.findByText('其他页已有成员');await waitFor(()=>expect(organizationApi.memberRelations).toHaveBeenCalledWith('org',['existing']));const row=screen.getAllByRole('checkbox')[1];expect(row).toBeDisabled();expect(row).toBeChecked();expect(screen.getByRole('button',{name:'保存关联'})).toBeDisabled();});
import userEvent from '@testing-library/user-event';
it('切换组织加载失败清空旧名单并禁止提交',async()=>{
 const user=userEvent.setup();vi.mocked(organizationApi.listTree).mockResolvedValue([{id:'a',name:'学校A',status:'ENABLED',effectiveStatus:'ENABLED',children:[]},{id:'b',name:'学校B',status:'ENABLED',effectiveStatus:'ENABLED',children:[]}] as any);vi.mocked(organizationApi.members).mockResolvedValueOnce({items:[{id:'u',displayName:'学校A用户',username:'auser',status:'ENABLED'}],page:1,pageSize:20,total:1} as any).mockRejectedValueOnce(new Error('学校B加载失败'));
 render(<UserPickerModal open title="关联用户" requireOrganization actionPrefix="iam.role-users" onClose={()=>{}} onSubmit={async()=>{}}/>);await user.click(screen.getByRole('combobox'));await user.click(await screen.findByText('学校A'));await screen.findByText('学校A用户');await user.click(screen.getByRole('combobox'));await user.click(await screen.findByText('学校B'));await screen.findByText('学校B加载失败');expect(screen.queryByText('学校A用户')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'保存关联'})).toBeDisabled();
});
