package com.lingdong.learning.feature.web;

/** 客户端启动前可读取的非敏感功能能力摘要。 */
public record PublicCapabilityResponse(
        String client,
        boolean studentCodeLoginEnabled,
        boolean studentQrLoginEnabled,
        boolean studentWechatAuthEnabled,
        boolean parentRelationshipManagementEnabled,
        boolean organizationMiniappAuthEnabled,
        boolean organizationManagementEnabled,
        boolean studentOrganizationRelationshipEnabled,
        boolean accountSecurityManagementEnabled,
        boolean parentAccountLifecycleEnabled,
        boolean parentMobileManualRecoveryEnabled,
        boolean studentAccountCancellationEnabled,
        boolean learningTaskManagementEnabled,
        boolean classManagementEnabled,
        boolean previousDayTaskCopyEnabled,
        boolean learningTaskTemplateEnabled,
        boolean growthPointQueryEnabled,
        boolean growthPointCorrectionEnabled,
        boolean rewardExchangeEnabled,
        boolean dailyGrowthReviewEnabled,
        boolean periodicGrowthReportEnabled,
        boolean dictionaryManagementEnabled,
        boolean cacheManagementEnabled,
        boolean interfaceServiceManagementEnabled,
        boolean attachmentServiceEnabled,
        boolean importExportTemplateManagementEnabled,
        boolean dataImportValidationEnabled,
        boolean dataExportEnabled,
        boolean studentBatchImportEnabled,
        boolean teacherManagementEnabled,
        boolean studentExceptionReportEnabled,
        boolean attendanceManagementEnabled,
        boolean growthReviewPdfExportEnabled,
        boolean growthReviewSubscriptionEnabled,
        boolean anonymousClassRankEnabled
) {
}
