import {useEffect,useRef,useState} from 'react';
import {Alert,Drawer,Form,Input,Space,Tag,message} from 'antd';
import {ViewportTable as Table} from '../../components/ViewportTable';
import {ConfiguredButton as Button} from '../../components/ConfiguredButton';
import {organizationApi,type OrganizationNode,type OrganizationMemberPage} from '../../api/organization';
import {UserPickerModal} from '../users/UserPickerModal';
import {CreateUserDrawer} from '../users/CreateUserDrawer';
export function OrganizationMembersDrawer({organization,onClose,embedded=false}:{organization:OrganizationNode;onClose:()=>void;embedded?:boolean}){
 const [page,setPage]=useState<OrganizationMemberPage>({items:[],page:1,pageSize:20,total:0});const [keyword,setKeyword]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string>();const [picker,setPicker]=useState<'members'|'administrators'>();const [create,setCreate]=useState(false);const request=useRef(0);const saving=useRef(false);const enabled=organization.effectiveStatus==='ENABLED'&&organization.status==='ENABLED';
 async function load(current=1,search=query){const serial=++request.current;setLoading(true);setError(undefined);try{const data=await organizationApi.members(organization.id,{page:current,pageSize:20,keyword:search});if(serial===request.current)setPage(data);}catch(e){if(serial===request.current)setError(e instanceof Error?e.message:'组织用户加载失败');}finally{if(serial===request.current)setLoading(false);}}
 useEffect(()=>{void load(1,'');return()=>{request.current++;};},[organization.id]);
 async function associate(ids:string[],administrator:boolean){if(saving.current)return;saving.current=true;setBusy(true);setError(undefined);try{await organizationApi.associateMembers(organization.id,ids,administrator);message.success(administrator?'组织管理员已添加':'组织用户已关联');await load(page.page);}finally{saving.current=false;setBusy(false);}}
 async function promote(id:string){try{await associate([id],true);}catch(e){setError(e instanceof Error?e.message:'设置管理员失败');}}
 const content=<div className="organization-members">
 {error&&<Alert type="error" message={error} action={<Button actionKey="organizations.members.retry" disabled={busy} onClick={()=>void load(page.page)}>重试</Button>}/>}
 <div className="content-panel" style={{padding:12,marginBottom:12}}><Form layout="inline" onFinish={()=>{setQuery(keyword);void load(1,keyword);}}><Form.Item label="账号或名称"><Input value={keyword} onChange={e=>setKeyword(e.target.value)} style={{width:230}} disabled={busy}/></Form.Item><Form.Item><Space><Button actionKey="organizations.members.query" htmlType="submit" type="primary" disabled={busy}>查询</Button><Button actionKey="organizations.members.reset" disabled={busy} onClick={()=>{setQuery('');setKeyword('');void load(1,'');}}>重置</Button></Space></Form.Item></Form></div>
 <div className="content-panel" style={{padding:12,marginBottom:12}}><Space wrap><Button actionKey="organizations.members.add" disabled={!enabled||busy} onClick={()=>setPicker('members')}>关联已有用户</Button><Button actionKey="organizations.members.add-admin" disabled={!enabled||busy} onClick={()=>setPicker('administrators')}>添加组织管理员</Button><Button actionKey="organizations.members.create" type="primary" disabled={!enabled||busy} onClick={()=>setCreate(true)}>新增用户</Button></Space></div>
 <Table rowKey="id" size="small" loading={loading} dataSource={page.items} columns={[{title:'账号',dataIndex:'username',width:130,ellipsis:true},{title:'名称',dataIndex:'displayName',width:120,ellipsis:true},{title:'身份',dataIndex:'administrator',width:110,render:value=>value?<Tag color="green">组织管理员</Tag>:<Tag>用户</Tag>},{title:'状态',dataIndex:'status',width:70,render:status=>status==='ENABLED'?'启用':status==='DISABLED'?'停用':status==='LOCKED'?'锁定':'已注销'},{title:'操作',width:125,fixed:'right',render:(_,user)=>!user.administrator&&<Button actionKey="organizations.members.promote" size="small" aria-label={`设为管理员-${user.displayName}`} disabled={!enabled||busy||user.status!=='ENABLED'} onClick={()=>void promote(user.id)}>设为管理员</Button>}]} pagination={{current:page.page,pageSize:20,total:page.total,showSizeChanger:false,onChange:current=>void load(current)}}/>
 {picker&&<UserPickerModal open title={picker==='administrators'?'添加组织管理员':'关联已有用户'} targetOrganizationId={organization.id} administratorMode={picker==='administrators'} actionPrefix={picker==='administrators'?'organizations.admin-picker':'organizations.member-picker'} existingUserIds={page.items.filter(u=>picker==='members'||u.administrator).map(u=>u.id)} onClose={()=>setPicker(undefined)} onSubmit={ids=>associate(ids,picker==='administrators')}/>}
 <CreateUserDrawer open={create} organization={organization} actionPrefix="organizations.create-user" onClose={()=>setCreate(false)} onSaved={()=>load(page.page)}/>
 </div>;
 return embedded?content:<Drawer open title={`组织用户 · ${organization.name}`} width="min(960px,96vw)" onClose={busy?undefined:onClose} closable={!busy} maskClosable={!busy} keyboard={!busy}>{content}</Drawer>;
}
