package com.lingdong.learning.iam.audit.application;

/** 身份权限管理中已经落地的变更事件类型。 */
public enum IamChangeAuditEventType {
    MENU_CREATE,
    MENU_UPDATE,
    MENU_REORDER,
    USER_CREATE,
    USER_PROFILE_CHANGE,
    USER_PASSWORD_RESET,
    USER_STATUS_CHANGE,
    USER_ORGANIZATION_ASSOCIATE,
    USER_ROLE_ASSIGN,
    ROLE_CREATE,
    PERMISSION_CREATE,
    ROLE_PERMISSION_CONFIGURE,
    ROLE_PERMISSION_REMOVE,
    USER_PERMISSION_CONFIGURE,
    USER_PERMISSION_REMOVE,
    ROLE_DATA_SCOPE_ADD,
    ORGANIZATION_ADMIN_ASSIGN
}
