import {useEffect,useMemo,useRef,useState} from 'react';
import {Alert,Modal,Select,Spin,Tree,message} from 'antd';
import {ConfiguredButton as Button} from '../../components/ConfiguredButton';
import {iamApi,type Permission,type PermissionAssignment} from '../../api/iam';
import type {ManagedUser} from '../../api/users';
import type {MenuNode} from '../../api/menus';
import {ApiRequestError} from '../../api/http';
import {treeCheckState,type PermissionTreeNode} from './rolePermissionTree';
import {buildUserPermissionTree,toggleUserPermissionBranch,userTreeCheckState} from './userPermissionTree';
interface Props{open:boolean;user?:ManagedUser;users?:ManagedUser[];permissions?:Permission[];onClose:()=>void;actionPrefix?:string;}
export function UserPermissionTreeModal({open,user,users=[],permissions,onClose,actionPrefix='users.permission-tree'}:Props){
 const [userId,setUserId]=useState<string>();const [menus,setMenus]=useState<MenuNode[]>([]);const [catalog,setCatalog]=useState<Permission[]>([]);const [assignments,setAssignments]=useState<PermissionAssignment[]>([]);const [inherited,setInherited]=useState<string[]>([]);const [denied,setDenied]=useState<string[]>([]);const [selected,setSelected]=useState(new Set<string>());const [loading,setLoading]=useState(false);const [ready,setReady]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const request=useRef(0);const saveLock=useRef(false);
 const locked=useMemo(()=>new Set(inherited),[inherited]);const tree=useMemo(()=>buildUserPermissionTree(menus,catalog,assignments,inherited,denied),[menus,catalog,assignments,inherited,denied]);const checked=useMemo(()=>userTreeCheckState(tree,selected),[tree,selected]);
 async function load(id:string){const serial=++request.current;setUserId(id);setLoading(true);setReady(false);setError(undefined);setMenus([]);setSelected(new Set());try{const [context,own,all]=await Promise.all([iamApi.userPermissionTree(id),iamApi.listUserPermissions(id),permissions?Promise.resolve(permissions):iamApi.listPermissions()]);if(serial!==request.current)return;setMenus(context.menus);setInherited(context.inheritedPermissionIds);setDenied(context.inheritedDeniedPermissionIds);setAssignments(own);setCatalog(all);setSelected(new Set([...own.filter(a=>a.effect==='ALLOW').map(a=>a.permissionId),...context.inheritedPermissionIds]));setReady(true);}catch(e){if(serial===request.current)setError(e instanceof Error?e.message:'权限加载失败');}finally{if(serial===request.current)setLoading(false);}}
 useEffect(()=>{if(open&&user)void load(user.id);else{request.current++;setUserId(undefined);setReady(false);setError(undefined);}return()=>{request.current++;};},[open,user?.id]);
 async function save(){if(!userId||!ready||saveLock.current)return;saveLock.current=true;setSaving(true);setError(undefined);const serial=request.current;const managedPermissionIds=[...new Set(tree.flatMap(n=>n.permissionIds))].filter(id=>!locked.has(id));const permissionIds=managedPermissionIds.filter(id=>selected.has(id));try{await iamApi.batchUserPermissions(userId,{permissionIds,managedPermissionIds,expectedAssignments:assignments});if(serial===request.current){setAssignments([...assignments.filter(a=>!managedPermissionIds.includes(a.permissionId)),...permissionIds.map(permissionId=>({permissionId,effect:'ALLOW' as const}))]);message.success('用户权限已保存');}}catch(e){if(serial===request.current){setError(e instanceof Error?e.message:'权限保存失败');if(e instanceof ApiRequestError&&e.status===409)setReady(false);}}finally{saveLock.current=false;setSaving(false);}}
 return <Modal title={user?`授权 · ${user.displayName}`:'配置用户权限'} centered open={open} width="min(880px,92vw)" onCancel={saving?undefined:onClose} closable={!saving} maskClosable={!saving} keyboard={!saving} footer={[<Button actionKey={`${actionPrefix}.cancel`} key="cancel" disabled={saving} onClick={onClose}>取消</Button>,<Button actionKey={`${actionPrefix}.save`} key="save" type="primary" loading={saving} disabled={!ready||loading} onClick={()=>void save()}>保存用户权限</Button>]}>
 {user?<div style={{marginBottom:16}}>{user.displayName}（{user.username}）</div>:<><label htmlFor="user-permission-subject">用户</label><Select id="user-permission-subject" value={userId} style={{width:'100%',marginBottom:16}} disabled={saving} showSearch optionFilterProp="label" options={users.map(u=>({value:u.id,label:`${u.displayName}（${u.username}）`}))} onChange={id=>void load(id)}/></>}
 {error&&<Alert type="error" message={error} action={<Button actionKey={`${actionPrefix}.retry`} disabled={saving} onClick={()=>userId&&void load(userId)}>重新加载</Button>}/>}
 <Spin spinning={loading}>{ready&&<Tree<PermissionTreeNode> height={Math.max(180,window.innerHeight-300)} checkable checkStrictly treeData={tree} checkedKeys={checked} disabled={saving} onCheck={(_,info)=>setSelected(prev=>toggleUserPermissionBranch(info.node,prev,info.checked,locked))}/>}</Spin>
 </Modal>;
}
